(function(root){
'use strict';
root.createPacketRenderer=function(canvas,engine){
const C=PacketCore,ctx=canvas.getContext('2d'),{width:W,height:H,danger:FAIL,origin:ORIGIN,left:WALL_L,right:WALL_R}=C.FIELD;
let effects=[],labels=[],shake=0,angle=-Math.PI/2;
function packet(x,y,type,alpha=1,scale=1){const t=C.TYPES[type],r=19*scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/3*i-Math.PI/6;const px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fillStyle=t.color+'23';ctx.fill();ctx.strokeStyle=t.color;ctx.lineWidth=1.7;ctx.stroke();ctx.beginPath();ctx.moveTo(-8,-12);ctx.lineTo(3,-12);ctx.strokeStyle=t.color+'80';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=t.color;ctx.font='bold '+(12*scale)+'px Consolas, monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.glyph,0,1);ctx.fillStyle=t.color+'70';ctx.fillRect(-5,10,3,2);ctx.fillRect(1,10,3,2);ctx.restore();}

function trajectory(){const trace=engine.preview(angle),type=C.TYPES[engine.current];ctx.save();ctx.strokeStyle=type.color;ctx.globalAlpha=.55;ctx.lineWidth=3;ctx.lineCap='round';ctx.setLineDash([1,14]);ctx.beginPath();trace.path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);ctx.restore();if(trace.cell){const p=C.point(trace.cell.r,trace.cell.c,0,engine.parity);packet(p.x,p.y,engine.current,.3);}}
function render(aim){angle=aim;const {board,offset,current,shot}=engine;ctx.clearRect(0,0,W,H);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.strokeStyle='#20324655';ctx.lineWidth=1;for(let x=32;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=24;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.strokeStyle='#476b7f55';ctx.beginPath();ctx.moveTo(WALL_L,0);ctx.lineTo(WALL_L,FAIL-12);ctx.moveTo(WALL_R,0);ctx.lineTo(WALL_R,FAIL-12);ctx.stroke();ctx.fillStyle='#6b8a9e';for(let y=16;y<FAIL-15;y+=32){ctx.fillRect(25,y,3,1);ctx.fillRect(612,y,3,1);}const danger=[...board.values()].some(p=>C.point(p.r,p.c,offset,engine.parity).y>500);ctx.strokeStyle=danger?'#f77c8580':'#a8666a60';ctx.setLineDash([6,7]);ctx.beginPath();ctx.moveTo(44,FAIL);ctx.lineTo(596,FAIL);ctx.stroke();ctx.setLineDash([]);ctx.font='9px Consolas,monospace';ctx.textAlign='center';ctx.fillStyle=danger?'#fa8b96':'#996a78';ctx.fillText('SATURATION BOUNDARY',320,FAIL+17);if(engine.state==='AIMING')trajectory();for(const p of board.values()){const pos=C.point(p.r,p.c,offset,engine.parity);packet(pos.x,pos.y,p.type);}for(const e of effects){if(e.fall)packet(e.x,e.y,e.type,Math.min(1,e.life*2));else{ctx.globalAlpha=e.life/e.max;ctx.fillStyle=e.color;ctx.fillRect(e.x,e.y,e.size,e.size);ctx.globalAlpha=1;}}// Router launcher
 ctx.save();ctx.translate(ORIGIN.x,ORIGIN.y);ctx.strokeStyle='#375465';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-53,17);ctx.lineTo(-53,-15);ctx.moveTo(53,17);ctx.lineTo(53,-15);ctx.stroke();ctx.fillStyle='#162b3a';ctx.strokeStyle='#476677';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(-65,7,130,34,8);ctx.fill();ctx.stroke();for(let i=0;i<5;i++){ctx.fillStyle=i<3?'#70e5cf':'#345062';ctx.fillRect(-46+i*10,23,5,3);}ctx.fillStyle='#8ba8b9';ctx.font='8px Consolas,monospace';ctx.textAlign='right';ctx.fillText('RTR–01',51,28);ctx.rotate(angle+Math.PI/2);ctx.fillStyle='#203f4b';ctx.strokeStyle='#709caa';ctx.beginPath();ctx.roundRect(-10,-34,20,38,5);ctx.fill();ctx.stroke();ctx.restore();if(!shot)packet(ORIGIN.x,ORIGIN.y,current);else packet(shot.x,shot.y,shot.type);ctx.textAlign='center';for(const l of labels){ctx.globalAlpha=Math.min(1,l.life*3);ctx.fillStyle='#0b1521da';ctx.fillRect(l.x-132,l.y-20,264,l.sub?54:36);ctx.fillStyle='#b6ffeb';ctx.font='bold 19px Consolas,monospace';ctx.fillText(l.text,l.x,l.y);ctx.font='10px Consolas,monospace';ctx.fillStyle='#a2bdce';ctx.fillText(l.sub,l.x,l.y+21);}ctx.globalAlpha=1;ctx.restore();}

function event(name,data={}){
 if(name==='start'){effects=[];labels=[];shake=0;return;}
 if(name==='route')for(const p of data.packets){const pos=C.point(p.r,p.c,0,engine.parity);for(let i=0;i<7;i++)effects.push({...pos,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,life:.28,max:.28,color:C.TYPES[p.type].color,size:3});}
 if(name==='drop')for(const p of data.packets)effects.push({...C.point(p.r,p.c,0,engine.parity),vx:(Math.random()-.5)*100,vy:80,life:1.3,max:1.3,type:p.type,fall:true});
 if(name==='score'){labels.push({x:Math.max(140,Math.min(500,data.at.x)),y:Math.max(100,data.at.y),text:'ROUTED +'+data.total.toLocaleString(),sub:data.fallen?data.fallen+' DROPPED / '+data.streak+'x STREAK':data.streak>1?data.streak+'x ROUTING STREAK':'',life:1.3});if(data.fallen>=4||data.streak>=3)shake=5;}
 if(name==='traffic')labels.push({x:320,y:535,text:'INCOMING TRAFFIC',sub:'A NEW ROW JOINS THE NETWORK',life:1.3});
}
function update(dt){for(const e of effects){e.life-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.fall)e.vy+=750*dt;}effects=effects.filter(e=>e.life>0);for(const l of labels){l.life-=dt;l.y-=dt*18;}labels=labels.filter(l=>l.life>0);shake=Math.max(0,shake-dt*20);}
return{render,event,update};
};
})(globalThis);
