(function(){
'use strict';
const C=PacketCore,S=PacketStates,$=id=>document.getElementById(id),canvas=$('game'),format=n=>n.toLocaleString(),sound=PacketSound,keys=new Set();
let renderer,angle=-Math.PI/2,best=0,last=0,lastState=null;
try{best=Number(sessionStorage.getItem('packet-route-level-best'))||0;}catch(_){}
const engine=new PacketEngine({emit:onEvent});renderer=createPacketRenderer(canvas,engine);
function onEvent(name,data){renderer?.event(name,data);const audio={start:'route',route:'route',drop:'drop',traffic:'warning',complete:'combo',saturated:'end',fire:'fire',wall:'wall',swap:'swap'};if(audio[name])sound.play(audio[name]);}
function saveBest(){if(engine.score<=best)return;best=engine.score;try{sessionStorage.setItem('packet-route-level-best',String(best));}catch(_){}}
function resultRow(label,value){const row=document.createElement('div'),name=document.createElement('span'),number=document.createElement('strong');name.textContent=label;number.textContent=value;row.append(name,number);return row;}
function showOverlay(){const state=engine.state,overlay=$('overlay');if(![S.READY,S.PAUSED,S.LEVEL_COMPLETE,S.NETWORK_SATURATED].includes(state)){overlay.hidden=true;return;}overlay.hidden=false;$('result').replaceChildren();$('result').hidden=state===S.READY||state===S.PAUSED;
 if(state===S.READY){$('overlay-title').textContent='Make the connection.';$('overlay-kicker').textContent='LEVEL 01 / FIRST CONNECTION';$('overlay-copy').textContent='Clear every packet before the network saturates. Match 3 of a kind; the field advances every '+engine.config.advanceEvery+' shots, or sooner after misses.';$('play').textContent='START LEVEL 1 ↗';}
 else if(state===S.PAUSED){$('overlay-title').textContent='Connection on hold.';$('overlay-kicker').textContent='NETWORK PAUSED';$('overlay-copy').textContent='Your turn is saved, including any packets in motion.';$('play').textContent='RESUME ROUTING ↗';}
 else{const clear=state===S.LEVEL_COMPLETE;$('overlay-title').textContent=clear?'NETWORK CLEARED':'NETWORK SATURATED';$('overlay-kicker').textContent='LEVEL '+engine.level+' / '+engine.config.name.toUpperCase();$('overlay-copy').textContent=clear?'Every packet is off the network. Your next route awaits.':'The packet field reached the saturation boundary. Try this layout again.';$('play').textContent=clear?'CONTINUE TO LEVEL '+(engine.level+1)+' ↗':'RETRY LEVEL '+engine.level+' ↻';$('result').append(resultRow(clear?'Level score':'Final score',format(engine.score)),resultRow('Packets routed',format(engine.routed)),resultRow('Packets dropped',format(engine.dropped)),resultRow('Accuracy',Math.round(engine.accuracy*100)+'%'),resultRow('Completion bonus','+'+format(engine.bonus)));$('announcement').textContent=$('overlay-title').textContent+'. Level '+engine.level+'. Score '+engine.score;}
 $('overlay-help').textContent=state===S.PAUSED?'PRESS P TO RESUME':'AIM · MATCH · CLEAR THE NETWORK';if(state!==S.READY)$('play').focus();
}
function refresh(){saveBest();const {state,current,next,config}=engine,aiming=state===S.AIMING;let bottom=0;for(const p of engine.board.values())bottom=Math.max(bottom,C.point(p.r,p.c,engine.offset,engine.parity).y+C.R);const pressure=Math.min(100,Math.round(bottom/C.FIELD.danger*100));
 $('score').textContent=format(engine.score);$('best').textContent=format(best);$('delivered').textContent=format(engine.routed);$('dropped').textContent=format(engine.dropped);$('streak').textContent=engine.streak?engine.streak+'×':'—';$('time').textContent=String(Math.floor(engine.elapsed/60)).padStart(2,'0')+':'+String(Math.floor(engine.elapsed%60)).padStart(2,'0');$('pressure').textContent=pressure+'%';$('pressure-bar').style.width=pressure+'%';$('pressure-bar').style.background=pressure>80?'#fa799d':'#70e5cf';$('status').textContent=state===S.NETWORK_SATURATED?'Saturated':state===S.LEVEL_COMPLETE?'Cleared':state===S.PAUSED?'On hold':pressure>80?'Heavy traffic':'Flowing freely';
 $('level-label').textContent='LEVEL '+String(engine.level).padStart(2,'0');$('level-name').textContent=config.name.toUpperCase();$('board-state').textContent=state.replaceAll('_',' ');$('congestion-count').textContent=engine.allowance+' / '+config.allowance;$('advance-count').textContent=Math.max(0,config.advanceEvery-engine.turnsSinceTraffic)+' SHOTS TO ADVANCE';$('congestion-dots').textContent='● '.repeat(engine.allowance)+'○ '.repeat(config.allowance-engine.allowance);$('congestion-dots').setAttribute('aria-label',engine.allowance+' unsuccessful shots until incoming traffic');
 const t=C.TYPES[next],loaded=C.TYPES[current];$('next-packet').style.setProperty('--packet',t.color);$('next-packet').firstElementChild.textContent=t.label;$('next-name').textContent=t.name;$('loaded-packet').textContent=loaded.label;$('loaded-packet').style.setProperty('--packet',loaded.color);$('queued-packet').textContent=t.label;$('queued-packet').style.setProperty('--packet',t.color);$('swap').disabled=!aiming;$('swap').setAttribute('aria-label','Swap current '+loaded.label+' with next '+t.label);$('queue-status').textContent=aiming?'CLICK NEXT OR PRESS X TO SWAP':state.replaceAll('_',' ');$('pause').disabled=[S.READY,S.LEVEL_COMPLETE,S.NETWORK_SATURATED].includes(state);$('pause').textContent=state===S.PAUSED?'▶':'Ⅱ';$('pause').setAttribute('aria-label',state===S.PAUSED?'Resume game':'Pause game');
 if(state!==lastState){showOverlay();lastState=state;}
}
function pause(){if(engine.pause()){keys.clear();refresh();if(engine.state!==S.PAUSED)canvas.focus();}}
function swap(){if(engine.swap()){refresh();canvas.focus();}}
function fire(){engine.fire(angle);refresh();}
function aim(e){if(engine.state!==S.AIMING)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*C.FIELD.width/rect.width,y=(e.clientY-rect.top)*C.FIELD.height/rect.height;angle=Math.max(-Math.PI+.12,Math.min(-.12,Math.atan2(Math.min(-8,y-C.FIELD.origin.y),x-C.FIELD.origin.x)));}
canvas.addEventListener('pointermove',aim);let touchPointer=null;
canvas.addEventListener('pointerdown',e=>{if(engine.state!==S.AIMING||e.button>0)return;canvas.focus();aim(e);if(e.pointerType==='mouse')fire();else{touchPointer=e.pointerId;canvas.setPointerCapture(e.pointerId);}});
canvas.addEventListener('pointerup',e=>{if(e.pointerId!==touchPointer)return;touchPointer=null;aim(e);fire();});canvas.addEventListener('pointercancel',()=>touchPointer=null);
window.addEventListener('keydown',e=>{if(['KeyP','Escape'].includes(e.code)&&!e.repeat){pause();return;}if(e.code==='KeyX'&&!e.repeat){e.preventDefault();swap();return;}if(e.target.tagName==='BUTTON')return;if(['ArrowLeft','ArrowRight','Space'].includes(e.code)){e.preventDefault();keys.add(e.code);if(e.code==='Space'&&!e.repeat)fire();}});window.addEventListener('keyup',e=>keys.delete(e.code));
function autoPause(){keys.clear();touchPointer=null;if(![S.READY,S.PAUSED,S.LEVEL_COMPLETE,S.NETWORK_SATURATED].includes(engine.state))pause();}window.addEventListener('blur',autoPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)autoPause();});
 $('play').onclick=()=>{if(engine.state===S.PAUSED){pause();return;}engine.start(engine.state===S.LEVEL_COMPLETE?engine.level+1:engine.level);angle=-Math.PI/2;keys.clear();refresh();canvas.focus();};$('swap').onclick=swap;$('pause').onclick=pause;$('sound').onclick=()=>{sound.enabled=!sound.enabled;$('sound').textContent=sound.enabled?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',String(sound.enabled));$('sound').setAttribute('aria-label',sound.enabled?'Disable sound':'Enable sound');sound.play('route');};
 refresh();function frame(now){const dt=Math.min((now-last)/1000,.035);last=now;if(engine.state===S.AIMING){if(keys.has('ArrowLeft'))angle=Math.max(-Math.PI+.12,angle-dt*1.5);if(keys.has('ArrowRight'))angle=Math.min(-.12,angle+dt*1.5);}if(engine.state!==S.PAUSED)renderer.update(dt);engine.update(dt);renderer.render(angle);refresh();requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();

