(() => {
  'use strict';
  const G=PacketBingo,$=id=>document.getElementById(id);
  let state=G.createState(),untilCall=0,lastTick=performance.now(),soundOn=false,audio=null,best=0,helpPaused=false,busy=false,generation=0;
  let records={level:1,bingos:0,combo:0,multiplier:1};
  try{records={...records,...JSON.parse(localStorage.getItem('packet-bingo-records')||'{}')};}catch{}
  const seenCards=new Set([G.cardKey(state.card)]);
  try{best=Number(localStorage.getItem('packet-bingo-best'))||0;}catch{}
  const time=ms=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
  function tone(kind){if(!soundOn)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.connect(v);v.connect(audio.destination);o.frequency.value=kind==='invalid'?145:kind==='win'?880:540;v.gain.setValueAtTime(.055,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2);}catch{}}
  function feedback(message,error=false){$('feedback').textContent=message;$('feedback').classList.toggle('error',error);}
  function renderBoard(){const board=$('board');board.replaceChildren();state.card.forEach((item,index)=>{const b=document.createElement('button');b.className='node';b.dataset.id=item.id;b.dataset.category=item.category;b.classList.toggle('free',index===12);b.innerHTML=`<span class="node-icon" aria-hidden="true">${index===12?item.icon:item.number}</span><span class="node-name">${item.name}</span><span class="node-state"></span>`;b.addEventListener('click',()=>choose(item.id,b));board.append(b);});updateBoard();}
  function updateBoard(){const winners=new Set(state.routes.flat());[...$('board').children].forEach((b,i)=>{const item=state.card[i],marked=state.marked.has(item.id);b.classList.toggle('marked',marked);b.classList.toggle('winner',winners.has(i));b.classList.toggle('objective-square',!!state.config.pattern&&G.patterns[state.config.pattern].includes(i));b.classList.toggle('power',state.powers.has(item.id));b.setAttribute('aria-pressed',String(marked));b.setAttribute('aria-label',`${item.number||'FREE'}, ${item.name}, ${marked?'discovered':'unknown'}`);b.querySelector('.node-state').textContent=i===12?'127.0.0.1 / FREE':marked?'✓ DISCOVERED':state.powers.has(item.id)?state.powers.get(item.id).toUpperCase()+' POWER':'NODE UNKNOWN';});$('discovered-count').textContent=`${String(state.marked.size).padStart(2,'0')} / 25 NODES`;renderRoutes();}
  function renderRoutes(){const svg=$('routes');svg.replaceChildren();function line(a,b,cls){const el=document.createElementNS('http://www.w3.org/2000/svg','line');const point=i=>[(i%5)*100+50,Math.floor(i/5)*100+50];const [x1,y1]=point(a),[x2,y2]=point(b);Object.entries({x1,y1,x2,y2,class:cls}).forEach(([k,v])=>el.setAttribute(k,v));svg.append(el);}if(state.routes.length){state.routes.forEach(r=>line(r[0],r[4],'route-line'));}else{G.lines.forEach(r=>r.slice(0,4).forEach((a,i)=>{if(state.marked.has(state.card[a].id)&&state.marked.has(state.card[r[i+1]].id))line(a,r[i+1],'potential-line');}));}}
  function renderLog(){$('log-count').textContent=String(state.history.length).padStart(2,'0');if(!state.history.length){$('log').innerHTML='<li class="empty-log">Listening for network activity…<small>Discovered events will appear here.</small></li>';return;}$('log').innerHTML=state.history.map(item=>`<li><span class="log-icon" aria-hidden="true">${item.icon}</span><div>${'BINGO'[Math.floor((item.number-1)/15)]}-${item.number} · ${item.name}<small>${time(state.called.get(item.id))} / ${item.category.toUpperCase()}</small></div><span class="log-status">${state.marked.has(item.id)?'✓':'•'}</span></li>`).join('');}
  function saveRecords(){best=Math.max(best,state.score);records.level=Math.max(records.level,Number(state.network));records.bingos=Math.max(records.bingos,state.totalBingos);records.combo=Math.max(records.combo,state.bestCombo);records.multiplier=Math.max(records.multiplier,state.highestMultiplier);try{localStorage.setItem('packet-bingo-best',String(best));localStorage.setItem('packet-bingo-records',JSON.stringify(records));}catch{}}
  function renderStats(){$('score').textContent=String(state.score).padStart(5,'0');$('correct').textContent=state.correct;$('mistakes').textContent=state.mistakes;$('elapsed').textContent=time(state.elapsed);$('best').textContent=best;$('accuracy').textContent=state.correct+state.mistakes?Math.round(state.correct/(state.correct+state.mistakes)*100)+'%':'-';renderProgress();}
  function renderProgress(){const c=state.config,parts=G.objectiveProgress(state);$('network-id').textContent=`LEVEL / ${String(state.network).padStart(3,'0')}`;$('level-type').textContent=c.type;$('objective').textContent=c.description;$('objectives').replaceChildren(...parts.map(p=>{const row=document.createElement('div');row.textContent=`${p.done?'✓ ':''}${p.label}: ${p.value.toLocaleString()} / ${p.target.toLocaleString()}`;return row;}));const percent=Math.round(parts.reduce((sum,p)=>sum+Math.min(1,p.value/p.target),0)/parts.length*100);$('level-progress').value=percent;$('level-progress').textContent=percent+'%';$('unlock').textContent=c.unlock?`UNLOCK · ${c.unlock}`:'Build chains. Save power daubs for your multiplier.';$('challenge-limit').textContent=c.timeLimit?`Challenge time left: ${time(Math.max(0,c.timeLimit-state.elapsed))}`:'No timer · all earlier calls remain playable';$('arcade-stats').textContent=`BINGOs ${state.totalBingos} · Combo ${state.combo} · Multiplier x${state.multiplier}`;$('records').textContent=`RECORDS · Level ${records.level} · BINGOs ${records.bingos} · Combo ${records.combo} · x${records.multiplier}`;}
  function controls(){$('scan').disabled=state.won||state.failed||busy||state.paused||!state.deck.length;$('scan').innerHTML=state.deck.length?(state.started?'Next scan <span>→</span>':'Start scanning <span>→</span>'):'Scan complete <span>✓</span>';$('pause').disabled=!state.started||state.won||state.failed||busy;$('pause').textContent=state.paused?'Resume':'Pause';document.body.classList.toggle('paused',state.paused||!state.started||state.won||state.failed||busy);$('scanner-note').textContent=state.failed?'Run ended. Play again.':state.won?'Network complete. All routes verified.':state.paused?'Scanner paused. Take your time.':!state.deck.length?'All events logged. Match any remaining called nodes.':$('auto').checked?(state.config.timeLimit?'Timed challenge. Earlier calls remain playable.':'No time limit. Earlier calls remain playable.'):'Manual scanning. Advance whenever you’re ready.';}
  function scan(){if(busy)return;const item=G.callNext(state);if(!item)return;untilCall=state.config.interval;$('event-message').textContent=item.eventMessage;$('call-icon').textContent=item.icon;$('call-name').textContent=`${'BINGO'[Math.floor((item.number-1)/15)]}-${item.number} · ${item.name}`;const onCard=state.card.some(x=>x.id===item.id);$('call-hint').textContent=onCard?'Find this number on your card.':'Not on your card. Keep scanning.';feedback(onCard?`${item.name.toUpperCase()} detected. Find and select its node.`:`${item.name.toUpperCase()} logged. This node isn’t on your card.`);tone('call');G.checkOutcome(state);updateBoard();renderLog();controls();if(state.failed)gameOver();}
  async function choose(id,button){if(busy)return;const result=G.select(state,id);if(result.kind==='ignored')return;if(result.kind==='invalid'){button.classList.remove('invalid');void button.offsetWidth;button.classList.add('invalid');feedback(`INVALID NODE · Wait until this name appears in the network log.${result.points?` ${result.points} points`:''}`,true);tone('invalid');renderStats();return;}busy=true;const token=generation;updateBoard();renderLog();controls();button.classList.add('daub-pulse');for(const event of result.events){if(token!==generation)return;feedback(`${event.label}${event.points?' · +'+event.points.toLocaleString():''}`);tone(event.label.includes('BINGO')?'win':'correct');$('cascade').textContent=event.label+(event.points?' +'+event.points.toLocaleString():'');await new Promise(resolve=>setTimeout(resolve,260));}if(token!==generation)return;busy=false;$('cascade').textContent='';saveRecords();renderStats();controls();if(state.won)finish();else if(state.failed)gameOver();}
  function gameOver(){saveRecords();renderStats();controls();$('game-over-reason').textContent=state.failureReason;$('game-over-stats').textContent=`Score ${state.score.toLocaleString()} · Level ${state.network} · BINGOs ${state.totalBingos} · Best combo ${state.bestCombo} · Highest multiplier x${state.highestMultiplier}. High score ${best.toLocaleString()} · Highest level ${records.level}.`;$('game-over-dialog').showModal();}
  function finish(){if(state.score>best){best=state.score;try{localStorage.setItem('packet-bingo-best',String(best));}catch{}}renderStats();controls();feedback('NETWORK COMPLETE · Your route is online.');$('win-stats').innerHTML=[['Level completed',state.network],['Score',state.score.toLocaleString()],['Scan time',time(state.elapsed)],['Correct discoveries',state.correct],['Incorrect selections',state.mistakes],['BINGOs this level',state.routes.length],['Best combo',state.levelBestCombo],['Highest multiplier','x'+state.levelHighestMultiplier],['Level bonus','+'+state.bonus.toLocaleString()]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');$('win-dialog').querySelector('h2').textContent=`LEVEL ${state.network} COMPLETE!`;$('perfect').textContent=state.levelMistakes===0?`PERFECT SCAN · +${G.scoring.perfect} BONUS`:'ROUTE VERIFIED · CONNECTION ESTABLISHED';$('win-dialog').showModal();}
  function reset(advance=false){generation++;busy=false;$('cascade').textContent='';$('game-over-dialog').close();state=advance?G.advanceNetwork(state,seenCards):G.createState($('difficulty').value,G.freshCard(G.difficulties[$('difficulty').value].pool,seenCards),1);const network=state.network;untilCall=0;lastTick=performance.now();$('win-dialog').close();$('network-id').textContent=`LEVEL / ${String(network).padStart(3,'0')}`;$('event-message').textContent='READY TO DISCOVER';$('call-name').textContent='Stand by';$('call-icon').textContent='⌁';$('call-hint').textContent='Your next connection is out there.';$('scan-progress').style.width='0';feedback('Ready when you are. Start a scan to find your first node.');saveRecords();renderBoard();renderLog();renderStats();controls();}
  $('scan').addEventListener('click',scan);$('new-game').addEventListener('click',()=>reset());$('next-network').addEventListener('click',()=>reset(true));$('play-again').addEventListener('click',()=>reset());$('difficulty').addEventListener('change',()=>reset());$('auto').addEventListener('change',()=>{untilCall=state.config.interval;controls();});$('pause').addEventListener('click',()=>{state.paused=!state.paused;controls();});$('sound').addEventListener('click',()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(soundOn));tone('call');});$('help').addEventListener('click',()=>{helpPaused=state.paused;state.paused=true;controls();$('help-dialog').showModal();});$('help-dialog').addEventListener('close',()=>{state.paused=helpPaused;lastTick=performance.now();controls();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
  $('restart-run').addEventListener('click',()=>reset());
  document.addEventListener('visibilitychange',()=>{lastTick=performance.now();});
  setInterval(()=>{const now=performance.now(),dt=now-lastTick;lastTick=now;if(document.hidden||!state.started||state.paused||state.won||state.failed||busy)return;state.elapsed+=dt;G.checkOutcome(state);renderProgress();if(state.failed){gameOver();return;}$('elapsed').textContent=time(state.elapsed);if($('auto').checked&&state.deck.length){untilCall-=dt;$('scan-progress').style.width=`${Math.min(100,100*(1-untilCall/state.config.interval))}%`;if(untilCall<=0)scan();}else $('scan-progress').style.width=state.deck.length?'0':'100%';},100);
  renderBoard();renderStats();controls();
})();


